### ISSUE TITLE
Not supporting Laravel 8

### ISSUE THREAD

**Issue by dhruva81** [techsemicolon/laravel-php-latex#6]
![image](https://user-images.githubusercontent.com/42173738/93424947-b74a2180-f8d6-11ea-8dd8-aa0f7f160fa7.png)

**Comment by PaulMcRoar** [comment]
Not sure if it's a complete test , but dryRun() works fine if I just add version 8.0 in composer.json

require": {
        "php": "^7.4",
        "illuminate/support": "^7.0 || ^8.0",
        "illuminate/filesystem": "^7.0 || ^8.0",
        "symfony/process": "^5.0"
    },

**Comment by dhruva81** [comment]
Hi Thank you 

But I am still not able to install using composer require

**Comment by PaulMcRoar** [comment]
You could use my fork for now, I've a pull request pending.

i.e. in your composer.json "require"

        "techsemicolon/laravel-php-latex" : "dev-master"

and then add to repositories

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/PaulMcRoar/laravel-php-latex"
        }
    ]   

Keep an eye on this project though as if my pull request is approved then you should change it back.

**Comment by dhruva81** [comment]
Hi @PaulMcRoar 

Thank you for reply.

Unfortunately  I am getting errors

```
Error
Class 'Techsemicolon\Latex' not found 

```

I am received this error while composer update
![image](https://user-images.githubusercontent.com/42173738/103019044-26858080-456c-11eb-9933-a37d4bd35bc0.png)
